resources:
- name: sources
  type: git
  source:
    uri: git@github.com:mvandewouw/DevOpsTraining.git
    branch: master
    private_key: ((private-repo-key))
- name: sources-write # Name of the resource
  type: git # Resource type
  source:
    uri: git@github.com:mvandewouw/DevOpsTraining.git
    private_key: ((private-repo-key))
    branch: master


jobs:
- name: build
  plan:
  - get: sources
    trigger: true
  - task: build software
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8-alpine} # Docker container to build in
      inputs:
        - name: sources # Use the source resource
      run:
        path: ./gradlew # Command to execute
        args: ["build", "-x", "test"]
        dir: sources/application # Location to execute, note the 'sources' as directory prefix


- name: test
  plan:
  - get: sources
    trigger: true
    passed: [build]
  - task: unit-test
    file: sources/CI/task-unit-test.yml


- name: deploy # Name of the job
  serial: true # No parallel execution of the plan
  plan:
  - get: sources # Download the sources
    trigger: true
    passed: [test] # Trigger after job test has passed
  - task: tag, publish and publish new version
    file: sources/CI/task-deploy.yml
  - put: sources-write
    params: {repository: sources-output} # Push latest version after tagging en version bump
